### ISSUE TITLE
Creating a Stock object yields a 401 Forbidden error

### ISSUE THREAD

**Issue by SixBeeps** [JadenSWang/Stock-Wrapper#6]
Attempting to create a Stock object causes the HTTP request to return a 401.
![image](https://user-images.githubusercontent.com/19637928/82330450-db413900-99b0-11ea-8ee0-a2858607d40a.png)

**Comment by JadenSWang** [comment]
Thanks for letting me know. I overlooked the level of authentification needed for robinhood to cough up their data on prices, I’d you have a robinhood account, you can use login through stock_wrapper.robin.login(email, password) I should have a fix for this by tomorrow.
